### ISSUE TITLE
Join page looks like the mockups 

### ISSUE THREAD

**Issue by utunga** [CashlessSociety/cashless-ui#51]
On desktop:
https://www.figma.com/proto/sq4aGgw7IQAbuRkXcFTaap/Cashless?node-id=1166%3A21710&scaling=min-zoom

![desktop](https://user-images.githubusercontent.com/12442114/111928821-92e73000-8b19-11eb-97a4-a1a42e2b6c15.png)

On mobile:
https://www.figma.com/proto/sq4aGgw7IQAbuRkXcFTaap/Cashless?node-id=1166%3A21772&scaling=min-zoom

![image](https://user-images.githubusercontent.com/12442114/111928866-bc07c080-8b19-11eb-9122-368141937a0b.png)

**Acceptance criteria from the parent epic - #7** 

-[ ] as anon i can signup choose a name and profile and post things to my feed immediately

**Comment by sarah-arrrgh** [comment]
Brain thoughts 🧠 

- why does body content spill over footer?
- what was `.wrapper` being used for in `SignupPage.js`? (I removed it and replaced it with .page-header...)
- why does `.page-header` stop the body content from hiding behind the topnav, but not from spilling over the footer?

**Comment by sarah-arrrgh** [comment]
More brain thoughts:

- hide "Join" button when on signup page??
-

**Comment by sarah-arrrgh** [comment]
SignUp page 

`
  return (
    <>
      <TopNavbar isAuthenticated={isAuthenticated} />

      {/* 
        this places content below the navbar and centers it. 
        it changes the font colour from black to white, which seems to be a css styling thing when .page-header and .container are combined... 
        not sure what else it's doing... 
        pulled it from creativetim example signup page component styling to fix problem of content disappearing under navbar 
        .page-header:before - this seems to be resonsible for making the background grey */}
      <div className="page-header">
      {/* <div className='wrapper'> */}
        <div className="content">

          <SignupForm storageKeys={storageKeys} />
          {/* removing this for now as it's so huge and silly! and the content spills over the top of it confusingly */}
          {/* <FooterSocial /> */}
        </div>
      </div>
    </>
`

**Comment by sarah-arrrgh** [comment]
This is ready for @karenkun to come and make it look good!

There's some funky css stuff going on here, I got some of the way to figuring it out (see comments in code history, and particularly the above code snippet from `SignupPage.js` with the comments included (which I've removed now for cleanliness ✨ ). 

Here's a maybe helpful summary:
- the `.wrapper` div seemed to not keep the content from disappearing behind the navbar. the `.page-header` seemed to do the trick, but then all the text was rendered white and the bg grey
- `.page-header:before` seems to be responsible for making the bg grey
- `.page-header` + `.container`seems to be responsible for making the text white


Higher level thoughts: 🧠 
My ideal situation is that we stick the navbar and footer on some much higher level component (like `index.js`) so that we're placing content between the two at all times, without having to figure out how to make it work on each view. Roughly like this (though I'm not sure off hand where it would fit around the `BrowserRouter` stuff):

index.js
...
`
<Navbar />
<div className="actual-content" >
        <Route
          path='/join'
          render={(props) => (
            <SignupPage
              {...props}
              isAuthenticated={isAuthenticated}
              secret={secret}
              storageKeys={storageKeys}
            />
          )}
        />
</div>
<Footer />
`
...

**Comment by sarah-arrrgh** [comment]
Oh! I forgot, I will hide the "Join" button when on this view before submitting a PR

**Comment by sarah-arrrgh** [comment]
I have used the creativetim ImageUpload component for the profile image upload - @karenkun to confirm this is fine (and maybe update figma??)

**Comment by sarah-arrrgh** [comment]
Higher level thoughts: 🧠 
My ideal situation is that we stick the navbar and footer on some much higher level component (like `index.js`) so that we're placing content between the two at all times, without having to figure out how to make it work on each view. Roughly like this (though I'm not sure off hand where it would fit around the `BrowserRouter` stuff):

index.js


```
<Navbar />
<div className="actual-content" >
        <Route
          path='/join'
          render={(props) => (
            <SignupPage
              {...props}
              isAuthenticated={isAuthenticated}
              secret={secret}
              storageKeys={storageKeys}
            />
          )}
        />
</div>
<Footer />
```

**Comment by utunga** [comment]
It's looking great now. Not sure all the people involved but good enough for this issue. Couple styling issues once you are actually logged in but we can addres those later.
